FROM python:3.11

WORKDIR /usr/src/app

COPY ./helpers_pkg ./helpers_pkg
COPY ./models_pkg ./models_pkg
COPY ./secrets_pkg ./secrets_pkg
COPY ./requirements.txt .
COPY ./client.py .

RUN apt-get update && apt-get install build-essential -y
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD ["uvicorn", "client:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]