FROM python:3.11

WORKDIR /usr/src/app

COPY . .

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

CMD uvicorn client:app --proxy-headers --host 0.0.0.0 --port 80